### ISSUE TITLE
Fix npm scripts

### ISSUE THREAD

**Issue by shakedmanes** [rabiran/authorization-server#23]
### Todo:

- [x]  Add simple `npm start` script
- [x]  Add script to generate certificates for the server (for https)
- [x]  Fix the `copy-files` script for certificates
- [x]  Add script for creating `env` file automaticly when building (with parameters like port etc.)
