### ISSUE TITLE
Add testing for the whole server features

### ISSUE THREAD

**Issue by shakedmanes** [rabiran/authorization-server#50]
### Todo:
Add testing to the following features:
- [ ] All OAuth2 implemented flows
- [ ] All OAuth2 Client Management API
- [ ] Token introspection endpoint
- [ ] Refresh Token Flow
- [ ] JWT validations and generations
- [ ] All Other features not mentioned above
